// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyWEYF87ZJt-WnGcjUhoOk_sbH1Fw7a5Q',
    appId: '1:763041440708:web:b8717ccc55d8bb5ea2ba91',
    messagingSenderId: '763041440708',
    projectId: 'hiresync-42115',
    authDomain: 'hiresync-42115.firebaseapp.com',
    storageBucket: 'hiresync-42115.firebasestorage.app',
    measurementId: 'G-J7H41SPRM4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDttQX4beEvEtEQyQxMd9P8JK764uJsWwg',
    appId: '1:763041440708:android:e51cec2fec9bbb59a2ba91',
    messagingSenderId: '763041440708',
    projectId: 'hiresync-42115',
    storageBucket: 'hiresync-42115.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASjqHvpZWNCOw1BosEZCAe7SUD_FxrFGw',
    appId: '1:763041440708:ios:95650145992e4178a2ba91',
    messagingSenderId: '763041440708',
    projectId: 'hiresync-42115',
    storageBucket: 'hiresync-42115.firebasestorage.app',
    iosBundleId: 'com.example.hiresync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASjqHvpZWNCOw1BosEZCAe7SUD_FxrFGw',
    appId: '1:763041440708:ios:95650145992e4178a2ba91',
    messagingSenderId: '763041440708',
    projectId: 'hiresync-42115',
    storageBucket: 'hiresync-42115.firebasestorage.app',
    iosBundleId: 'com.example.hiresync',
  );
}
